

services:
  db:
    image: postgres:13
    env_file:
      - ngabo.env



    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Corrected volume definition

  web:
    build: .
    command: gunicorn family_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/Ngabo
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    volumes:
      - ./ngabo/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web


volumes:
  postgres_data:  # Define the volume here
