# Generated by Django 5.1.5 on 2025-02-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_messages', '0002_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
