# Generated by Django 5.1.5 on 2025-02-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_messages', '0003_message_audio_alter_message_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='audio',
        ),
        migrations.AlterField(
            model_name='message',
            name='contents',
            field=models.TextField(default=''),
        ),
    ]
