# Generated by Django 5.1.5 on 2025-02-06 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family_messages',
            old_name='image_massage',
            new_name='image_message',
        ),
        migrations.RenameField(
            model_name='family_messages',
            old_name='text_mesages',
            new_name='text_message',
        ),
        migrations.AddField(
            model_name='family_messages',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
